[package]
name = "teal-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1", features = ["macros"] }
reqwest = { version = "0.12.18", features = ["json"] }
dotenvy = "0.15.7"
anyhow = "1.0.98"
